/*
 * svr-bj
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Card : A single playing card with a rank and suit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Card {
    #[serde(rename = "rank")]
    pub rank: models::Rank,
    #[serde(rename = "suit")]
    pub suit: models::Suit,
}

impl Card {
    /// A single playing card with a rank and suit.
    pub fn new(rank: models::Rank, suit: models::Suit) -> Card {
        Card {
            rank,
            suit,
        }
    }
}

