/*
 * svr-bj
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Game : a game between one player and one dealer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Game {
    #[serde(rename = "dealer")]
    pub dealer: Box<models::Hand>,
    #[serde(rename = "player")]
    pub player: Box<models::Player>,
    #[serde(rename = "state")]
    pub state: models::State,
}

impl Game {
    /// a game between one player and one dealer
    pub fn new(dealer: models::Hand, player: models::Player, state: models::State) -> Game {
        Game {
            dealer: Box::new(dealer),
            player: Box::new(player),
            state,
        }
    }
}

