/*
 * svr-bj
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Hand : Represents a player's or dealer's hand.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Hand {
    #[serde(rename = "cards")]
    pub cards: Vec<models::Card>,
    pub value: u16,
}

impl Hand {
    /// Represents a player's or dealer's hand.
    pub fn new(cards: Vec<models::Card>, value: u16) -> Hand {
        Hand { cards, value }
    }
}
