/*
 * svr-bj
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Player : Represents a player.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Player {
    #[serde(rename = "bet")]
    pub bet: i32,
    #[serde(rename = "hand")]
    pub hand: Box<models::Hand>,
    #[serde(rename = "wealth")]
    pub wealth: i32,
}

impl Player {
    /// Represents a player.
    pub fn new(bet: i32, hand: models::Hand, wealth: i32) -> Player {
        Player {
            bet,
            hand: Box::new(hand),
            wealth,
        }
    }
}

