/*
 * svr-bj
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// State : state of one game waiting for bet, ongoing, winner
/// state of one game waiting for bet, ongoing, winner
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "WaitingBet")]
    WaitingBet,
    #[serde(rename = "Ongoing")]
    Ongoing,
    #[serde(rename = "PlayerJack")]
    PlayerJack,
    #[serde(rename = "DealerJack")]
    DealerJack,
    #[serde(rename = "PlayerBust")]
    PlayerBust,
    #[serde(rename = "DealerBust")]
    DealerBust,
    #[serde(rename = "PlayerWin")]
    PlayerWin,
    #[serde(rename = "DealerWin")]
    DealerWin,
    #[serde(rename = "Push")]
    Push,

}

impl std::fmt::Display for State {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::WaitingBet => write!(f, "WaitingBet"),
            Self::Ongoing => write!(f, "Ongoing"),
            Self::PlayerJack => write!(f, "PlayerJack"),
            Self::DealerJack => write!(f, "DealerJack"),
            Self::PlayerBust => write!(f, "PlayerBust"),
            Self::DealerBust => write!(f, "DealerBust"),
            Self::PlayerWin => write!(f, "PlayerWin"),
            Self::DealerWin => write!(f, "DealerWin"),
            Self::Push => write!(f, "Push"),
        }
    }
}

impl Default for State {
    fn default() -> State {
        Self::WaitingBet
    }
}

