/*
 * svr-bj
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Suit : Represents the four suits of a card deck.
/// Represents the four suits of a card deck.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Suit {
    #[serde(rename = "Hearts")]
    Hearts,
    #[serde(rename = "Diamonds")]
    Diamonds,
    #[serde(rename = "Clubs")]
    Clubs,
    #[serde(rename = "Spades")]
    Spades,

}

impl std::fmt::Display for Suit {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Hearts => write!(f, "Hearts"),
            Self::Diamonds => write!(f, "Diamonds"),
            Self::Clubs => write!(f, "Clubs"),
            Self::Spades => write!(f, "Spades"),
        }
    }
}

impl Default for Suit {
    fn default() -> Suit {
        Self::Hearts
    }
}

