name: CI Meson

on:
  workflow_dispatch:
  push:
    paths:
      - "**.cpp"
      - "**.hpp"
      - ".github/workflows/**"

jobs:
  build:
    name: Build and Test on ${{ matrix.os }} with Meson
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: actions/cache@v4
        with:
          path: builddir/
          key: ${{ runner.arch }}-${{ runner.os }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install meson ninja

      - name: Configure Project
        run: meson setup -Dclient=true -Dserver=true --reconfigure builddir/

      - name: compile
        run: meson compile -C builddir/ -v

      - name: whatsup
        shell: bash
        run: |
          ls -lA
          ls -l builddir/

      - name: Upload compilation log
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.os }}_Meson_Testlog
          path: builddir/meson-logs/*

          
      - name: Set executable name variables
        id: set_vars
        shell: bash
        run: |
          SYS=$(echo "${{ runner.arch }}-${{ runner.os }}" | tr '[:upper:]' '[:lower:]' | sed "s/x64/x86_64/" | sed "s/arm64/aarch64/")

          echo "artifact_name=blackjackpp-${SYS}" >> "$GITHUB_OUTPUT"

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_vars.outputs.artifact_name }}
          path: builddir/blackjackpp-(client|server)(.exe|)
