name: Automatic trigger draft release on tag push

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  call-build:
    uses: ./.github/workflows/build.yml

  auto-release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    needs: call-build
    steps:
      - uses: actions/checkout@v5

      - name: Download prebuilt binary artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: List all downloaded release-artifacts
        run: ls -lARh release-artifacts

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v2
        with:
          # draft: true
          generate_release_notes: true
          files: release-artifacts/**
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
